apiVersion: v1
kind: Service
metadata:
  name: booking-service
spec:
  selector:
    app: booking-service     # Service automatically finds every pod with this label -> this is the "Target Group"
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP             # only reachable from inside the cluster; exposed externally via Ingress
